# Tugas 5 Pencarian Dokumen
# Nama : Prio Budi Laksono
# NIM : 210411100177

# Transformasi SVD Dari TF-IDF

In [2]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD
from sklearn.metrics.pairwise import cosine_similarity
import re
from IPython.display import display, Markdown

# 1. Membaca Dataset
# Membaca file CSV yang berisi dataset
df = pd.read_csv("preprocessing-kompas.csv")

# Mengganti nilai NaN dengan string kosong agar tidak ada data kosong yang menyebabkan error
df['stopword_removal'] = df['stopword_removal'].fillna('')

# 2. Mengonversi Data Teks ke TF-IDF
# Menginisialisasi TfidfVectorizer dengan normalisasi L2
vectorizer = TfidfVectorizer(norm='l2')

# Menghitung nilai TF-IDF untuk setiap dokumen
tfidf_matrix = vectorizer.fit_transform(df['stopword_removal'])

# Mengubah hasil TF-IDF menjadi DataFrame untuk kemudahan akses
tfidf_df = pd.DataFrame(tfidf_matrix.toarray(), columns=vectorizer.get_feature_names_out())

In [3]:
tfidf_df.head(100)

,abang,abdullah,ac,acara,accessories,adangan,adaptif,adat,adil,aditya,...,youtube,yoy,yuk,yunus,zahaby,zaky,zona,zonasi,zoonosis,zwolle
0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
1,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
2,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
3,0.0,0.000000,0.0,0.027377,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.040729,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
4,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
96,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
97,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
98,0.0,0.041462,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
99,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.063146,0.0,0.000000,0.0,0.0,0.0,0.035781,0.0,0.0,0.0

In [9]:
# 3. Reduksi Dimensi dengan Truncated SVD
# Menginisialisasi TruncatedSVD untuk mereduksi dimensi menjadi 100 komponen (atau sesuai kebutuhan)
svd = TruncatedSVD(n_components=3800, random_state=42)

# Mengaplikasikan SVD pada matriks TF-IDF untuk menghasilkan matriks dengan dimensi yang lebih rendah
svd_matrix = svd.fit_transform(tfidf_matrix)

# Menyimpan hasil SVD dalam DataFrame untuk digunakan dalam perhitungan kemiripan
svd_df = pd.DataFrame(svd_matrix)

# Menampilkan 10 baris pertama dari DataFrame hasil SVD
svd_df.head(1000)

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,0.058818,0.098048,0.699340,-0.002821,0.016072,-0.001816,0.008370,-0.014020,-0.018418,0.006316,...,-0.013383,-0.007182,0.012910,-0.005387,0.011301,0.020558,-0.013914,0.003783,0.016848,0.016782
1,0.047102,0.068590,0.662212,0.004406,0.027243,0.001649,0.009544,-0.001154,-0.010573,0.003102,...,0.006192,0.010486,-0.008058,-0.003289,0.000497,-0.011377,0.016642,-0.004207,-0.014741,-0.017270
2,0.085543,0.315491,-0.022708,0.009887,0.082788,0.046388,0.104856,-0.292937,0.036663,-0.025507,...,-0.045216,0.012395,0.055289,0.001233,-0.011916,0.030831,0.050494,-0.015803,-0.013496,-0.000343
3,0.166815,0.580883,-0.052997,-0.021125,0.047945,0.039624,0.060439,-0.127161,0.014023,-0.002471,...,-0.005993,0.003475,-0.020156,-0.001967,-0.001832,-0.014074,0.033193,0.009926,0.006564,0.002532
4,0.046508,0.088619,0.787558,-0.012365,0.024126,0.001318,0.007906,0.003124,-0.001383,0.001437,...,0.002224,0.000658,0.003717,0.002685,-0.000778,0.013036,0.002142,0.006670,-0.001508,0.026336
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0.082718,0.004797,0.009747,0.044433,-0.045867,0.073335,0.013462,-0.035565,0.034215,-0.014573,...,0.000409,0.005474,0.000172,-0.001193,0.001915,0.003161,-0.001389,-0.001949,0.001368,-0.000487
96,0.491673,-0.111527,-0.011332,-0.120096,0.031230,-0.061586,0.097119,0.030476,0.035506,0.007619,...,-0.015778,0.007414,0.006106,0.006172,-0.016083,-0.001027,0.002856,0.008010,-0.014323,0.000193
97,0.419841,-0.094332,0.003707,-0.157419,-0.055309,0.107123,-0.168673,-0.074079,0.154774,-0.176337,...,-0.004682,0.001292,0.000205,0.000763,-0.002984,0.002899,-0.002776,-0.009277,0.011542,0.000274
98,0.624567,-0.131122,-0.013070,-0.044249,0.059455,-0.115687,0.254330,0.093960,-0.041656,0.100834,...,0.004596,-0.003456,-0.012686,-0.063829,0.015096,-0.011320,0.011633,0.005196,0.006297,0.002257
99,0.264703,-0.023777,-0.003574,0.223713,-0.262963,0.453292,0.247412,0.100853,-0.043032,-0.092493,...,0.001243,0.013131,-0.011257,0.008439,0.010434,0.010160,0.001456,0.001827,0.005517,0.002770

# Mencari Dokumen dengan Cosine Similiarity

In [3]:
# Fungsi untuk mencari dokumen terkait
def search_documents(query, top_n=100, similarity_threshold=0.5):
    # 4. Menghitung TF-IDF untuk kalimat inputan
    query_tfidf = vectorizer.transform([query])
    
    # 5. Mengurangi dimensi kalimat inputan
    query_svd = svd.transform(query_tfidf)
    
    # 6. Menghitung kemiripan kosinus
    cosine_similarities = cosine_similarity(query_svd, svd_df)
    
    # 7. Menyaring hasil kemiripan berdasarkan threshold
    similar_indices = [
        idx for idx, score in enumerate(cosine_similarities[0])
        if score >= similarity_threshold
    ]
    
    # 8. Mengambil dokumen terkait berdasarkan threshold
    related_docs = df.iloc[similar_indices]
    
    # Membatasi jumlah dokumen yang diambil
    return related_docs.head(top_n)

# Input dari pengguna
input_query = input("Masukkan kalimat pencarian Anda: ")
related_documents = search_documents(input_query)

# Menampilkan dokumen terkait dengan detail yang diminta
print("=" * 50)
print(f"{'Dokumen Terkait':^50}")
print("=" * 50)
displayed_count = 0

for index, row in related_documents.iterrows():
    print(f"Dokumen #{displayed_count + 1}")
    print(f"Judul    : {row['judul']}")
    print(f"Tanggal  : {row['tanggal']}")
    print(f"Kategori : {row['kategori']}")
    print(f"Isi Berita:\n{row['isi_berita']}")
    print("-" * 50)  # Pemisah antar dokumen
    displayed_count += 1

# Menampilkan jumlah dokumen yang ditampilkan
print(f"\nJumlah dokumen yang ditampilkan: {displayed_count}")
print("=" * 50)

Masukkan kalimat pencarian Anda:  saddil ramdani raih

==================================================
                 Dokumen Terkait
==================================================
Dokumen #1
Judul    : Saddil Ramdani Raih Penghargaan di Liga Super Malaysia 2024-2025
Tanggal  : 29/10/2024, 17:58 WIB
Kategori : Timnas Indonesia
Isi Berita:
KOMPAS.com - Kabar gembira datang dari Saddil Ramdani yang kini berkarir di Liga Super Malaysia 2024-2025 bersama Sabah FC. Dalam pertandingan pekan ke-12 yang berlangsung di City Stadium Penang pada Jumat (25/10/2024), Saddil berhasil menunjukkan performa gemilang bersama Sabah FC. Menurut laporan dari Stadium Astro, ia dinyatakan sebagai pemain terbaik minggu ini, setelah mencetak gol pembuka pada menit kedua pertandingan melawan Penang. Gol tersebut berasal dari tendangan jarak jauh yang melengkung ke sudut gawang, menandai kembalinya Saddil ke performa terbaik setelah lama tidak membela timnas Indonesia. Terakhir kali ia berseragam merah putih adalah pada laga persahabatan melawan Libya pada Januari 2024. Baca juga: Jadwal Liga Italia Tengah Pekan Ini: AC Milan Vs Napoli Sabah FC akhirnya menang telak dengan skor 4-0, dengan tiga gol tambahan dari rekan-rekan setimnya: Gabriel Peres (6'), Stuart Wilkin (35'), dan Dominic Tan (50'). Saat ini, Sabah FC berada di posisi ketiga klasemen dengan 20 poin, selisih 14 poin dari pemuncak klasemen, Johor Darul Takzim, dan enam poin dari peringkat kedua, Selangor. Pada hari ini, Sabah FC akan berhadapan dengan Kedah dalam pertandingan pekan ke-13 yang dijadwalkan berlangsung pukul 17.45 WIB.
--------------------------------------------------

Jumlah dokumen yang ditampilkan: 1
==================================================